#!/bin/sh

picom -b --vsync --experimental-backends
feh --bg-fill "/opt/WP/mountians.jpg"
setxkbmap us,ru -option 'grp:alt_shift_toggle'

export QT_QPA_PLATFORMTHEME=qt5ct

# Statusbar loop
while true; do
    ubar
    sleep 1s    # Update time every second
done &

# relaunch DWM
while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
