#!/bin/sh

SEP="|"

#RAM_USAGE=$( free -h | awk '/Mem:/ { printf(" %5s/%s \n", $3, $2) }' )
#CPU_USAGE=$( mpstat 1 1 | awk '/Av/ {printf(" %s% \n", $(NF-9))}' )
LANG=$( xset -q|grep LED| awk '{ if (substr ($10,5,1) == 1) print "ru"; else print "en"; }' )
DATE_TIME=$(date +"%d.%m.%y %H:%M:%S")
BATT=$(cat /sys/class/power_supply/BAT0/capacity)
AUDIO=$(amixer -D default | sed -n 's/.*\[\([0-9]\+\)%.*/\1/p' | grep -m 1 .)

xsetroot -rv -name "  $LANG  🔋 $BATT%  🔊 $AUDIO%  $DATE_TIME  "
